### ISSUE TITLE
Separate template from content

### ISSUE THREAD

**Issue by anphil** [anphil/anphil.github.io#12]
In order to make reusing the template easier, the content should be separated from the template. Thanks to how Jekyll works, this is already the case for most of the page (navigation, project list page, project page) where the content is placed in configuration files and markdown files that can easily be swapped out. Parts that still need work are:

- [ ] **Landing page**: Take text from somewhere else instead of hard-coding it directly in the layout
- [ ] **Footer**: Store list of items in `_data` (just like the navigation)
- [ ] Create a separate repository just for the template/sample content
